# Generated by Django 2.1.11 on 2019-11-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("puppetmanager", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="classifications",
            field=models.ManyToManyField(to="puppetmanager.Classification"),
        )
    ]
