# Generated by Django 2.1.11 on 2019-11-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("puppetmanager", "0002_auto_20191101_1802")]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="classifications",
            field=models.ManyToManyField(null=True, to="puppetmanager.Classification"),
        )
    ]
